### ISSUE TITLE
Make Renew HC FAQ Doc

### ISSUE THREAD

**Issue by agrizzlyadams** [SOZOGlobal/Scrumban#29]

**Comment by agrizzlyadams** [comment]
@Cosmicceph Monica already has a running list of these questions, and I can help you find the right answers.

**Comment by Cosmicceph** [comment]
Alrighty!

**Comment by agrizzlyadams** [comment]
where are we at on this?

**Comment by Cosmicceph** [comment]
I reviewed it yesterday. Cleaned it up and sent it over to Heather for design.
