### ISSUE TITLE
HTML for Cancel Recurring Order

### ISSUE THREAD

**Issue by monica-amaro** [SOZOGlobal/Scrumban#37]
request for HTML template for Cancel Autoshipment to be emailed to Monica

**Comment by agrizzlyadams** [comment]
Monica needs HTML for a generic cancel recurring order email she can send on a case by case basis and change out the name and dist ID

**Comment by monica-amaro** [comment]
Test

**Comment by rideswithchrist** [comment]
Is this based on the style of our autoresponders? Need some clarity on content

**Comment by monica-amaro** [comment]
Yes the HTML Template that you already made for the autoshipment cancel for the new autoresponders

**Comment by monica-amaro** [comment]
What clarity are you needing?

**Comment by agrizzlyadams** [comment]
@Cosmicceph (Nick) should be hitting you up for what goes in it. turns out we did not do this email in the batch we redesigned.

**Comment by rideswithchrist** [comment]
@monica-amaro the clear kind :100:

**Comment by monica-amaro** [comment]
Maybe something like: Subject: Your recurring order was canceled at your request

Please note that you no longer have an Active Recurring Order with us, effective _____.

Your SOZO Recurring Order was canceled at your request.  We're sorry that you're no longer with us and hope that you'll reconsider us in the future. If you previously scheduled a payment, we've cancelled that payment and shipment. We do want to make you aware, as our valued Distributor, when you cancel the recurring order, you will no longer be Active or eligible for commissions. Also, any Carryover Volume you may have accrued will no longer continue to carryover and will reset to zero. Please call SOZO Global customer service if you have any other questions at 1-888-880-7696.

**Comment by Cosmicceph** [comment]
Hey, Monica. Thanks for writing that up! Looks like there wasn't a slot for that particular email in the autoresponder document. Do you mind if I adjust the email's tone and redact it?

**Comment by monica-amaro** [comment]
Absolutely! Do anything you like to it, :) wanted ya to know what we were needing.  make  magic!

**Comment by Cosmicceph** [comment]
Thanks, Monica! You set the foundation for an informative email—I'm just going to tinker with its structure to allow for a more conciliatory tone. I'll get back to you momentarily.

**Comment by Cosmicceph** [comment]
I'm going to go ahead and close this issue! Monica approved my adjustments to the copy (you're awesome, Monica!) and Corey's got the revisions on Slack. Case closed, I'd say.
