### ISSUE TITLE
Need a copy of the Renew HC Post Card

### ISSUE THREAD

**Issue by monica-amaro** [SOZOGlobal/Scrumban#61]
I need a soft copy of the Renew HC Post card that was given to Distributors at SOZOFest

**Comment by agrizzlyadams** [comment]
is this complete?

**Comment by monica-amaro** [comment]
yes it sure was.

**Comment by rideswithchrist** [comment]
Oh, Thanks for letting me know!

**Comment by monica-amaro** [comment]
I know we were waiting on feedback but no response yet, so I assume she was ok with it. Thank you!
