### ISSUE TITLE
Add Stories from Workflowy to The Waffle

### ISSUE THREAD

**Issue by agrizzlyadams** [SOZOGlobal/Scrumban#72]
Since we've put our scrumban board on waffle, we need to transfer all open stories from workflowy over.

Also, Monica does this system work for you to know where things are at and talk to us about it?

**Comment by monica-amaro** [comment]
Sure, did you want me to move over the marking stories as well?

**Comment by agrizzlyadams** [comment]
sure thing, absolutely.
